name: Nexus & Dockerhub CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: 'nexus-grayroot'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Push the Docker image to Github registry
        run: |
          docker login --username grayr0ot --password ${{secrets.GHCR_PASSWORD}} ghcr.io
          docker build . --tag ghcr.io/grayr0ot/sh-service-registry:latest
          docker push ghcr.io/grayr0ot/sh-service-registry:latest